name: acourtney-fish-octopus
channels:
  - pytorch
  - conda-forge
dependencies:
  - conda-forge::python
  - conda-forge::ipykernel
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::matplotlib
  - conda-forge::scipy
  - conda-forge::napari
  - conda-forge::pandas
  - conda-forge::scikit-image
  - conda-forge::seaborn
  - conda-forge::dask
  - conda-forge::cellpose
  - conda-forge::pip
  - conda-forge::imaris-ims-file-reader
  - conda-forge::ipywidgets
  - conda-forge::ipyfilechooser
